### PR TITLE
Vectorize no return

### PR DESCRIPTION
**Pull request by sizmailov**
Make CI pass

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Thanks! Hadn't noticed the CI had failed!

Why the `std::move` though? I thought returning a move was bad, as it inhibits return value optimization/copy elision?

**Comment by sizmailov** [comment]
In this case a copy is made because actual return type is different from function return type which disables NRVO see https://reviews.llvm.org/D43322

**Comment by sizmailov** [comment]
Another option I consider was changing return type from `py::object` to `returned_array::Type`, but it breaks with single values: `array` returned instead of `int`. `py::object` remains common denominator. 

I would do `merge & rebase & force-push` to make PR clear

**Comment by YannickJadoul** [comment]
Hmmm, yeah, ok, `py::object` is a weird kind of hierarchy of course :/ Let's just keep this, then. It's how it was before the change, so I agree on not using `returned_array::Type`.

> I would do merge & rebase & force-push to make PR clear

What exactly do you mean? Just clicking merge on your PR won't update the main PR on pybind11?

**Comment by sizmailov** [comment]
> What exactly do you mean? Just clicking merge on your PR won't update the main PR on pybind11?

It would of course. I meant to do it locally, not through github.

**Comment by YannickJadoul** [comment]
Sorry, still confused on what you're proposing to do. But let's see if this works. If necessary, we can still update history.

**Comment by YannickJadoul** [comment]
Thanks a lot, btw, for spotting these!

**Comment by YannickJadoul** [comment]
(cross-reference pybind/pybind11#1969)

**Pull request merged**
